#pragma once
#include "SolitudeHeaders.h"

/*contains all data needed to render a frame of a scene
generated by logic module and passed to graphics module
(ie GraphicsRenderer / ScreenManager)*/
class FrameData 
{
	std::vector<std::string> strings;
public:

};