#pragma once

enum GRAPHICS_MESSAGE_TYPES
{
	MESSAGE_LOAD_TEXTURE,
	MESSAGE_UNLOAD_TEXTURE,
	MESSAGE_FINISHED_CACHING,
	MESSAGE_FINISHING_UNCACHING,
};

struct GraphicsMessage
{
	GRAPHICS_MESSAGE_TYPES type;
};