#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>
#include <SFML/Window.hpp>
#include <memory>
#include <map>
#include <vector>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <iostream>